name = "Kodcu"
license = "GPLv2"
licenselink = "https://github.com/furkantokac/kodcu/blob/master/LICENSE.md"
description = "Kodcu is a fork of Mainroad theme and specialized to readibility of long posts."
homepage = "https://github.com/furkantokac/kodcu/"
tags = ["blog", "responsive", "widgets", "rss", "disqus", "google analytics", "wordpress"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]
min_version = "0.48"

[author]
  name = "Furkan Toka√ß"
  homepage = "https://github.com/furkantokac"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://github.com/Vimux/Mainroad"
  repo = "https://github.com/Vimux/Mainroad"
